#! /bin/bash
# ./scripts/update-grub
# SPDX-License-Identifier: GPL-3.0-or-later

if [ -f "/sys/firmware/efi" ]; 
then
    sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
else
    sudo grub2-mkconfig -o /boot/grub2/grub.cfg
fi